/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
export type { BMCManagement } from "./BMCManagement";
export type { BMCPeriphery } from "./BMCPeriphery";
export type { BMCService } from "./BMCService";
