/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Integers__factory } from "./Integers__factory";
export { Strings__factory } from "./Strings__factory";
