/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBMC__factory } from "./IBMC__factory";
export { IBSH__factory } from "./IBSH__factory";
export { ICallService__factory } from "./ICallService__factory";
export { ICallServiceReceiver__factory } from "./ICallServiceReceiver__factory";
export { IFeeManage__factory } from "./IFeeManage__factory";
